name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Tools
      run: |
        brew update && \
        brew install create-dmg
    - name: Build
      id: build
      run: |
        sudo xcode-select --switch /Applications/Xcode_26.2.app
        xcodebuild -project "RNGadget.xcodeproj/" -destination "generic/platform=macOS" -configuration Debug build CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO
    - name: Package DMG
      run: |
        mkdir Packaging/source_folder
        mv build/Debug/RNGadget.app Packaging/source_folder
        cd Packaging/
        chmod +x create-dmg.sh
        ./create-dmg.sh
    - name: Publish Build Files
      uses: actions/upload-artifact@v4
      with:
        path: Packaging/RNGadget-Installer.dmg
        name: RNGadget-Installer-latest.dmg

  build-ios:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build for iOS
      id: build-ios
      run: |
        sudo xcode-select --switch /Applications/Xcode_26.2.app
        xcodebuild -project "RNGadget.xcodeproj/" -target "RNGadget Mobile" -destination "generic/platform=iOS" -configuration Debug build CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO
    - name: Prepare Files and Create IPA File
      run: |
        mkdir ~/RNGadgetMobile
        mkdir ~/RNGadgetMobile/Payload
        mv build/Debug-iphoneos/RNGadget.app ~/RNGadgetMobile/Payload
        cp Packaging/iTunesArtwork ~/RNGadgetMobile/iTunesArtwork
        cd ~/RNGadgetMobile/
        zip -r RNGadget.zip *
        mv RNGadget.zip ~/RNGadget.ipa
    - name: Publish Build Files
      uses: actions/upload-artifact@v4
      with:
        path: ~/RNGadget.ipa
        name: RNGadget-latest.ipa
